Traceback (most recent call last):
  File "C:\Users\Noor\GitBash\mynewdir\streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
